### ISSUE TITLE
Usage docs leaves out a detail

### ISSUE THREAD

**Issue by Threadzless** [leona-ya/rocket_db_pools#1]
The usage docs doesn't specify that this:
```toml
[default.databases.sqlite_logs]
url = "/path/to/database.sqlite"
```
is intended to go into Rocket.toml, instead of Cargo.toml.

While trying to get this working, i spent a good twenty minutes trying to figure out why I was getting a "url is not set" error
